version: 2.1

executors:
  circle-jdk-executor:
    working_directory: ~/micrometer-release
    environment:
      GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx2048m -XX:+HeapDumpOnOutOfMemoryError"'
    docker:
      - image: cimg/openjdk:20.0.1
  machine-executor:
    working_directory: ~/micrometer-release
    machine:
      image: ubuntu-2204:2023.04.2

commands:
  gradlew-build:
    description: 'Run a Gradle build using the wrapper'
    parameters:
      command:
        type: string
        default: 'build'
    steps:
      - checkout
      - restore_cache:
          key: gradle-dependencies-{{ .Branch }}-{{ checksum "build.gradle" }}-{{ checksum ".circleci/config.yml" }}
      - run:
          name: downloadDependencies
          command: ./gradlew downloadDependencies --console=plain
      - save_cache:
          key: gradle-dependencies-{{ .Branch }}-{{ checksum "build.gradle" }}-{{ checksum ".circleci/config.yml" }}
          paths:
            - ~/.gradle
      - run:
          name: run gradle command
          command: ./gradlew << parameters.command >>
      - run:
          name: collect test reports
          when: always
          command: |
            mkdir -p ~/micrometer-release/test-results/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/micrometer-release/test-results/junit/ \;
      - store_test_results:
          path: ~/micrometer-release/test-results/
      - store_artifacts:
          path: ~/micrometer-release/test-results/

jobs:
  build:
    executor: circle-jdk17-executor
    steps:
      - gradlew-build

  deploy:
    executor: circle-jdk-executor
    steps:
      - checkout
      - restore_cache:
          key: gradle-dependencies-{{ .Branch }}-{{ checksum "build.gradle" }}-{{ checksum ".circleci/config.yml" }}
      - deploy:
          name: Deployment
          command: sh ./gradle/deploy.sh

workflows:
  version: 2
  build_prs_deploy_snapshots:
    jobs:
      - build
      - deploy:
          context:
            - deploy
          requires:
            - build
          filters:
            branches:
              only:
                - main
                - /\d+\.\d+\.x/
  build_deploy_releases:
    jobs:
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+(-(RC|M)\d+)?$/
      - build-jdk11:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+(-(RC|M)\d+)?$/
      - build-jdk17:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+(-(RC|M)\d+)?$/
      - docker-tests:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+(-(RC|M)\d+)?$/
      - deploy:
          context:
            - deploy
          requires:
            - build
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+(-(RC|M)\d+)?$/
